[package]
name = "icbiadb"
version = "0.1.0"
authors = ["Emanuel GS <grundligt@hotmail.com>"]
edition = "2018"
description = "KV & data structures database"
license = "MIT"
repository = "https://github.com/Grundligt/icbiadb"
keywords = ["database"]
categories = ["database", "database-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0.104", features=["derive"]}
bincode = "1.2.1"
async-std = {version="1.5.0", optional=true}
async-trait = {version="0.1.24", optional=true}
rayon = {version="1.3.0", optional=true}

log = "0.4.8"
env_logger = "0.7.1"

[features]
default = ["std"]
std = []
unstable = []
alloc = []
aio = ["async-trait", "rayon"]
async-std-comp = ["async-std", "aio"]


